// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt23t8ARpDvVk2Lx7PIgGnyx5y71G-3oM',
    appId: '1:128712349895:web:2e86069c7d7ca2e25f46e2',
    messagingSenderId: '128712349895',
    projectId: 'notas-e24f7',
    authDomain: 'notas-e24f7.firebaseapp.com',
    storageBucket: 'notas-e24f7.appspot.com',
    measurementId: 'G-Q21CEV7K93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpzG1EqXdde4dghpK-0zwIw2PqE9mwcg',
    appId: '1:128712349895:android:96a280898d1e44f95f46e2',
    messagingSenderId: '128712349895',
    projectId: 'notas-e24f7',
    storageBucket: 'notas-e24f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjtIf8PsjTWWrzFAOuBjBwdPREob5t18',
    appId: '1:128712349895:ios:c3cb5ec20125010a5f46e2',
    messagingSenderId: '128712349895',
    projectId: 'notas-e24f7',
    storageBucket: 'notas-e24f7.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCjtIf8PsjTWWrzFAOuBjBwdPREob5t18',
    appId: '1:128712349895:ios:c3cb5ec20125010a5f46e2',
    messagingSenderId: '128712349895',
    projectId: 'notas-e24f7',
    storageBucket: 'notas-e24f7.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt23t8ARpDvVk2Lx7PIgGnyx5y71G-3oM',
    appId: '1:128712349895:web:780e95cea114ffa05f46e2',
    messagingSenderId: '128712349895',
    projectId: 'notas-e24f7',
    authDomain: 'notas-e24f7.firebaseapp.com',
    storageBucket: 'notas-e24f7.appspot.com',
    measurementId: 'G-TFD0V6155J',
  );

}